### ISSUE TITLE
English model and Re-train

### ISSUE THREAD

**Issue by kris927b** [nedap/deidentify#33]
**Hi!** 👋 

Super cool repo and paper! 🎉 

Do you by chance have any pre-trained *English* model lying around that you would make available? 🔤 
Moreover, is it possible to use your dutch model and code to transfer to another domain? ➡️ 

**Hope you can help me!**

Best,
Kristian 👨‍🔬

**Comment by jantrienes** [comment]
Hi @kris927b,

Thanks for your questions!

> Do you by chance have any pre-trained English model lying around that you would make available? 🔤

We do have English models trained on the i2b2 and nursing notes datasets. Unfortunately, those datasets were obtained under a data use agreement (DUA) so I'm unsure if we are allowed to distribute the models.

However, It's not too complicated to train those models yourself with `deidentify`. You can take a look [here](https://github.com/nedap/deidentify/blob/master/docs/05_hsdm2020_english_datasets.md) for pointers on how to get the English data, and how to train the models.

> Moreover, is it possible to use your dutch model and code to transfer to another domain? ➡️

Yes, that should be possible. We use the [flair NLP](https://github.com/flairNLP/flair) library to train our neural models. Those are regular PyTorch models. So you could load them outside of deidentify, and continue training with your own data. 

```py
from flair.models import SequenceTagger
tagger = SequenceTagger.load(<path-to-pre-trained-dutch-model.pt>)

# Continue training with your data here
```

This probably assumes that you will end up with the same output tag-set. So either you harmonize your annotations to that tag set, or look into adapting the output layer. In the second case, it's probably best to ask on the flair/PyTorch repos. If you get around to implement some transfer learning, I would love to see if we can integrate this into the codebase somehow. So please keep me posted.

I hope this helps. If you have any follow up questions please let me know! 

Best regards,
Jan

**Comment by kris927b** [comment]
Hi @jantrienes 

Thank you so much for your answers! 🙏 
I will be looking into it, and if I make it to transfer your models, I will be opening a pull request so we can see if it can be integrated somehow. 😄 

Best,
Kristian
