### ISSUE TITLE
Language of the Evaluator's Tokenizer is set to English when asked for Dutch or French.

### ISSUE THREAD

**Issue by amobular** [nedap/deidentify#62]
The tokenizer of the `Evaluator` class, will be set to `TokenizerEN` when languages from `['nl', 'fr']` are chosen.

See the following code:
https://github.com/nedap/deidentify/blob/0e455d36a2cd7b05cf7d92c33a60face118c3890/deidentify/evaluation/evaluator.py#L45-L56

Change the `if` statements to `elif` and it will work as intended.

Nice project btw :)

**Comment by jantrienes** [comment]
Great catch! The fix should be simple: replace second and third if with `elif`. Do you mind submitting a PR?
